# Generated by Django 6.1.1 on 2026-09-29 05:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this category from the public filter list without deleting its notices.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in the filter dropdown.')),
            ],
            options={
                'verbose_name_plural': 'Notice categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(help_text='Full text shown on the notice page.')),
                ('reference_code', models.CharField(blank=True, help_text='Optional official code, for example JU/REG/2026/041.', max_length=40, null=True, unique=True)),
                ('published_date', models.DateField(help_text='The date printed on the notice.')),
                ('attachment', models.FileField(blank=True, help_text='Optional PDF. Maximum 10 MB.', null=True, upload_to='notices/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from the public notice board.')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned notices stay at the top of the list.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Cannot be deleted while notices still use it.', on_delete=django.db.models.deletion.PROTECT, related_name='notices', to='notice.noticecategory')),
            ],
            options={
                'verbose_name': 'notice',
                'verbose_name_plural': 'notices',
                'ordering': ['-is_pinned', '-published_date', '-id'],
            },
        ),
    ]
